# Generated by Django 6.0.7 on 2026-07-08 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=16, verbose_name='Пол')),
                ('blood_group', models.CharField(blank=True, choices=[('I+', 'I+'), ('I-', 'I-'), ('II+', 'II+'), ('II-', 'II-'), ('III+', 'III+'), ('III-', 'III-'), ('IV+', 'IV+'), ('IV-', 'IV-')], max_length=8, verbose_name='Группа крови')),
                ('pinfl', models.CharField(blank=True, help_text='Персональный идентификационный номер физического лица (14 цифр)', max_length=14, unique=True, verbose_name='ПИНФЛ')),
                ('passport', models.CharField(blank=True, help_text='Серия и номер паспорта гражданина Узбекистана (AB 1234567)', max_length=32, verbose_name='Паспорт')),
                ('foreign_passport', models.CharField(blank=True, help_text='Для иностранных граждан', max_length=64, verbose_name='Загранпаспорт / ID-карта иностранца')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram ID')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Адрес регистрации')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, verbose_name='Экстренный контакт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'), models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'), models.Index(fields=['pinfl'], name='patients_pa_pinfl_c7950b_idx'), models.Index(fields=['passport'], name='patients_pa_passpor_739d60_idx')],
            },
        ),
    ]
