# Generated by Django 5.1.15 on 2026-07-08 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=64)),
                ('pinfl', models.CharField(blank=True, max_length=14)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram_id', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('insurance_number', models.CharField(blank=True, max_length=64)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'), models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx')],
            },
        ),
    ]
