# Generated by Django 6.0.7 on 2026-07-11 09:30

from django.conf import settings
from django.db import migrations, models


def deduplicate_passports(apps, schema_editor):
    """Set duplicate passport values to empty string to allow unique constraint creation."""
    Patient = apps.get_model("patients", "Patient")
    from django.db.models import Count
    dupes = (
        Patient.objects
        .exclude(passport=None)
        .exclude(passport="")
        .values("passport")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for entry in dupes:
        matching = Patient.objects.filter(passport=entry["passport"]).order_by("created_at")
        first = matching.first()
        matching.exclude(pk=first.pk).update(passport="")


def reverse_dedup(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Allow null values on passport and pinfl
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, help_text='Серия и номер паспорта гражданина Узбекистана (AB 1234567)', max_length=32, null=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pinfl',
            field=models.CharField(blank=True, help_text='Персональный идентификационный номер физического лица (14 цифр)', max_length=14, null=True, verbose_name='ПИНФЛ'),
        ),
        # Step 2: Remove duplicate passport values (set them to empty string)
        migrations.RunPython(deduplicate_passports, reverse_dedup),
        # Step 3: Add unique constraints
        migrations.AlterField(
            model_name='patient',
            name='passport',
            field=models.CharField(blank=True, help_text='Серия и номер паспорта гражданина Узбекистана (AB 1234567)', max_length=32, null=True, unique=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pinfl',
            field=models.CharField(blank=True, help_text='Персональный идентификационный номер физического лица (14 цифр)', max_length=14, null=True, unique=True, verbose_name='ПИНФЛ'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(
                condition=models.Q(models.Q(('passport', None), _negated=True), models.Q(('passport', ''), _negated=True)),
                fields=('passport',),
                name='unique_passport_non_empty',
            ),
        ),
    ]
