# Generated by Django 5.1.15 on 2026-07-08 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_blood_group_patient_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pinfl',
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, help_text='ПИНФЛ/ИНН/ИИН/другое', max_length=64, verbose_name='Национальный идентификатор'),
        ),
        migrations.AddField(
            model_name='patient',
            name='oms_policy',
            field=models.CharField(blank=True, help_text='Номер полиса обязательного медицинского страхования', max_length=16, verbose_name='Полис ОМС'),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_series',
            field=models.CharField(blank=True, help_text='Серия паспорта РФ (4 цифры)', max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='patient',
            name='snils',
            field=models.CharField(blank=True, help_text='Страховой номер индивидуального лицевого счёта', max_length=14, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=512, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('I+', 'I+'), ('I-', 'I-'), ('II+', 'II+'), ('II-', 'II-'), ('III+', 'III+'), ('III-', 'III-'), ('IV+', 'IV+'), ('IV-', 'IV-')], max_length=8, verbose_name='Группа крови'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Экстренный контакт'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=16, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Номер паспорта РФ (6 цифр)', max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['snils'], name='patients_pa_snils_be1aea_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['oms_policy'], name='patients_pa_oms_pol_c5bb98_idx'),
        ),
    ]
