# Generated by Django 5.1.15 on 2026-07-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pinfl',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
    ]
