# Generated by Django 5.1.15 on 2026-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_phone_remove_user_pinfl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('chief_doctor', 'Главный врач'), ('doctor', 'Врач'), ('lab_tech', 'Лаборант'), ('registrar', 'Регистратор'), ('patient', 'Пациент')], default='patient', max_length=32, verbose_name='Роль'),
        ),
    ]
