# Generated by Django 5.1.15 on 2026-07-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('patients', '0002_add_passport_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Уникальный идентификатор чата Telegram', unique=True, verbose_name='Telegram Chat ID')),
                ('patient_id_str', models.CharField(blank=True, help_text="ID пациента в формате '1' или 'P-000001' (для обратной совместимости)", max_length=32, verbose_name='ID пациента (строка)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Подписка Telegram',
                'verbose_name_plural': 'Подписки Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chat_id'], name='notificatio_chat_id_593555_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_0277b7_idx')],
            },
        ),
    ]
