# Generated by Django 5.1.15 on 2026-07-08 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('hospitals', '0003_alter_department_options_alter_hospital_options_and_more'),
        ('patients', '0003_alter_patient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-scheduled_at'], 'verbose_name': 'Запись на приём', 'verbose_name_plural': 'Записи на приём'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Если известно заранее', null=True, verbose_name='Окончание приёма'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospitals.department', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=512, verbose_name='Причина обращения'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(verbose_name='Дата и время приёма'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('no_show', 'Неявка')], default='pending', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
