# Generated by Django 5.1.15 on 2026-07-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(blank=True, choices=[('therapy', 'Терапия'), ('surgery', 'Хирургия'), ('cardiology', 'Кардиология'), ('neurology', 'Неврология'), ('laboratory', 'Лаборатория'), ('xray', 'Рентген'), ('ultrasound', 'УЗИ'), ('reception', 'Приёмное отделение'), ('other', 'Другое')], default='other', max_length=32),
        ),
    ]
