# Generated by Django 6.0.7 on 2026-07-08 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnoses', models.JSONField(blank=True, default=list, help_text='Список диагнозов, например [{"code": "I10", "name": "Эссенциальная гипертензия", "date": "2025-01-01"}]', verbose_name='Диагнозы')),
                ('complaints', models.TextField(blank=True, verbose_name='Жалобы')),
                ('surgeries', models.JSONField(blank=True, default=list, help_text='Список операций, например [{"name": "Аппендэктомия", "date": "2024-06-15", "hospital": "ГКБ №1"}]', verbose_name='Операции')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Хронические заболевания')),
                ('allergies', models.TextField(blank=True, verbose_name='Аллергические реакции')),
                ('vaccinations', models.TextField(blank=True, verbose_name='Вакцинации')),
                ('medications', models.TextField(blank=True, verbose_name='Лекарственные назначения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки врача')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medrecords', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
                'ordering': ['-updated_at'],
            },
        ),
    ]
