# Generated by Django 5.1.15 on 2026-07-08 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='primary_diagnosis',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='complaints',
            field=models.TextField(blank=True, help_text='Жалобы пациента'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnoses',
            field=models.JSONField(blank=True, default=list, help_text='Список диагнозов'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='surgeries',
            field=models.JSONField(blank=True, default=list, help_text='Список операций'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='allergies',
            field=models.TextField(blank=True, help_text='Аллергии'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medications',
            field=models.TextField(blank=True, help_text='Назначения'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Заметки врача'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='vaccinations',
            field=models.TextField(blank=True, help_text='Вакцинации'),
        ),
    ]
