# Generated by Django 5.1.15 on 2026-07-08 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0002_remove_medicalrecord_primary_diagnosis_and_more'),
        ('patients', '0003_alter_patient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Медицинская карта', 'verbose_name_plural': 'Медицинские карты'},
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Аллергические реакции'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='chronic_conditions',
            field=models.TextField(blank=True, verbose_name='Хронические заболевания'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='complaints',
            field=models.TextField(blank=True, verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medrecords', to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnoses',
            field=models.JSONField(blank=True, default=list, help_text='Список диагнозов, например [{"code": "I10", "name": "Эссенциальная гипертензия", "date": "2025-01-01"}]', verbose_name='Диагнозы'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medications',
            field=models.TextField(blank=True, verbose_name='Лекарственные назначения'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки врача'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='surgeries',
            field=models.JSONField(blank=True, default=list, help_text='Список операций, например [{"name": "Аппендэктомия", "date": "2024-06-15", "hospital": "ГКБ №1"}]', verbose_name='Операции'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='vaccinations',
            field=models.TextField(blank=True, verbose_name='Вакцинации'),
        ),
    ]
