# Generated by Django 5.1.15 on 2026-07-08 15:48

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=files.models.upload_to),
        ),
    ]
