# Generated by Django 6.0.7 on 2026-07-08 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование анализа')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код анализа')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость')),
                ('currency', models.CharField(default='UZS', help_text='ISO валюта, например UZS/USD/RUB', max_length=8, verbose_name='Валюта')),
                ('turnaround_days', models.PositiveSmallIntegerField(default=1, verbose_name='Срок выполнения (дней)')),
                ('normal_range', models.CharField(blank=True, max_length=255, verbose_name='Референсные значения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вид анализа',
                'verbose_name_plural': 'Виды анализов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('ordered', 'Назначен'), ('in_progress', 'В работе'), ('completed', 'Готов'), ('verified', 'Проверен врачом'), ('sent', 'Отправлен пациенту')], default='created', max_length=32, verbose_name='Статус')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Данные результата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Лаборант (назначен)')),
                ('orderer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_orders', to='patients.patient', verbose_name='Пациент')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lab.analysistype', verbose_name='Вид анализа')),
            ],
            options={
                'verbose_name': 'Назначенный анализ',
                'verbose_name_plural': 'Назначенные анализы',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='lab_analysi_status_4d766f_idx')],
            },
        ),
    ]
