# Generated by Django 5.1.15 on 2026-07-08 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turnaround_days', models.PositiveSmallIntegerField(default=1)),
                ('normal_range', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Type',
                'verbose_name_plural': 'Analysis Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('ordered', 'Ordered'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('sent', 'Sent')], default='created', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('orderer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_analyses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_orders', to='patients.patient')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_analyses', to=settings.AUTH_USER_MODEL)),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lab.analysistype')),
            ],
            options={
                'verbose_name': 'Analysis Order',
                'verbose_name_plural': 'Analysis Orders',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='lab_analysi_status_4d766f_idx')],
            },
        ),
    ]
