# Generated by Django 5.1.15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("choice", "Выбор из списка"),
                            ("numeric", "Числовой"),
                            ("text", "Текст"),
                        ],
                        max_length=16,
                        verbose_name="Тип поля",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=255, verbose_name="Название поля"),
                ),
                (
                    "field_key",
                    models.SlugField(
                        max_length=64, verbose_name="Ключ поля (машинное имя)"
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text='Список вариантов для choice-типа, напр. ["O (I) Rh+", "A (II) Rh-"]',
                        null=True,
                        verbose_name="Варианты выбора",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "reference_range_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Мин. референс"
                    ),
                ),
                (
                    "reference_range_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Макс. референс"
                    ),
                ),
                (
                    "reference_range_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Референсные значения (текстом)",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Обязательное"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "analysis_type",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="fields",
                        to="lab.analysistype",
                        verbose_name="Вид анализа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поле результата анализа",
                "verbose_name_plural": "Поля результатов анализов",
                "ordering": ["analysis_type", "sort_order"],
                "unique_together": {("analysis_type", "field_key")},
            },
        ),
        migrations.CreateModel(
            name="AnalysisResultValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Значение")),
                (
                    "interpretation",
                    models.CharField(
                        blank=True,
                        choices=[("normal", "Норма"), ("high", "Повышен"), ("low", "Понижен")],
                        max_length=16,
                        verbose_name="Интерпретация",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="result_values",
                        to="lab.analysisfield",
                        verbose_name="Поле",
                    ),
                ),
                (
                    "analysis_order",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="result_values",
                        to="lab.analysisorder",
                        verbose_name="Заказ анализа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение результата",
                "verbose_name_plural": "Значения результатов",
                "unique_together": {("analysis_order", "field")},
            },
        ),
    ]