# Generated by Django 5.1.15 on 2026-07-08 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        ('patients', '0003_alter_patient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisorder',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Назначенный анализ', 'verbose_name_plural': 'Назначенные анализы'},
        ),
        migrations.AlterModelOptions(
            name='analysistype',
            options={'ordering': ['name'], 'verbose_name': 'Вид анализа', 'verbose_name_plural': 'Виды анализов'},
        ),
        migrations.AddField(
            model_name='analysisorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Лаборант (назначен)'),
        ),
        migrations.AddField(
            model_name='analysistype',
            name='currency',
            field=models.CharField(default='RUB', help_text='ISO валюта, например RUB/KZT/UZS', max_length=8, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='analysis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lab.analysistype', verbose_name='Вид анализа'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='orderer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Назначивший врач'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_orders', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='result',
            field=models.TextField(blank=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='result_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные результата'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('ordered', 'Назначен'), ('in_progress', 'В работе'), ('completed', 'Готов'), ('verified', 'Проверен врачом'), ('sent', 'Отправлен пациенту')], default='created', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='analysisorder',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код анализа'),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование анализа'),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='normal_range',
            field=models.CharField(blank=True, max_length=255, verbose_name='Референсные значения'),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='turnaround_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Срок выполнения (дней)'),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
